### ISSUE TITLE
Integrate the theme 

### ISSUE THREAD

**Issue by warrenrhodes** [karibu-cap/sabitou-clients#5]
integrate the theme base on the figma project:
https://www.figma.com/design/pHzaH12CC0gt4X3sLvJEOw/SABITOU?node-id=387-8287&node-type=frame&t=AXTctMRrrpR9iPUv-0

Reference:
- https://m3.material.io/blog/material-theme-builder
- https://material-foundation.github.io/material-theme-builder/
- https://flutter-shadcn-ui.mariuti.com (this package provide a great way to design the theme a also have the great reusable component)

fill free to choose what you want or make some proposal.

**Comment by Kurocifer** [comment]
okay @warrenrhodes I've checked the different references but which one will you advice because seeing all this is albeit confusing to me

**Comment by warrenrhodes** [comment]
> okay @warrenrhodes I've checked the different references but which one will you advice because seeing all this is albeit confusing to me

1 - First integrate https://pub.dev/packages/flex_color_scheme package. it allow to easily define the theme.  
2- Since the app page is not already setup the really see if the theme work, you can use https://rydmike.com/flexcolorscheme/themesplayground-latest/ to config the same theme ans see the change.
3 -  https://flutter-shadcn-ui.mariuti.com/ just allow to reuse the component but you can also use setup the custom theme created with flex_color_scheme
